### ISSUE TITLE
Unused method already implemented with different name

### ISSUE THREAD

**Issue by FrancescoScandiffio** [FrancescoScandiffio/shop-totem#17]
Method `allItemsRemoved()` is not implemented and has no reference in the project but is supposed to behave exactly as `clearOrderList()`. This seems to be a duplicate declaration that can be removed also from [interface TotemView](https://github.com/FrancescoScandiffio/shop-totem/blob/313c3ba498258a79eefc7dae02d80ff2e0ac0e80/raffaelliscandiffio.shop-totem/src/main/java/com/github/raffaelliscandiffio/view/TotemView.java).
https://github.com/FrancescoScandiffio/shop-totem/blob/313c3ba498258a79eefc7dae02d80ff2e0ac0e80/raffaelliscandiffio.shop-totem/src/main/java/com/github/raffaelliscandiffio/view/swing/TotemSwingView.java#L177-L186

However, i suggest keeping the name `allItemsRemoved` instead of `clearOrderList` for the following reasons:

1.  Name `clearOrderList` leaks implementation details of the view. The expected behaviour is to remove all objects from the view, no matter whether they are displayed as a list or a table.
2. Name `allItemsRemoved` sticks to the naming convention of the type 'itemAction' such as `itemAdded` and `itemRemoved` already present in the file.

**Comment by ClaudiaRaffaelli** [comment]
Yes it seems that there has been an oversight during the implementation of the methods. I think it is safe to proceed as you say.
