### ISSUE TITLE
GoodByePanel: add the panel and show it after the checkout

### ISSUE THREAD

**Issue by FrancescoScandiffio** [FrancescoScandiffio/shop-totem#23]

**Comment by FrancescoScandiffio** [comment]
We planned the insertion of a GoodBye panel to show after checkout instead of returning directly to the welcome page. This behaviour is already coded in TotemController but the Goodbye panel is to be done.
https://github.com/FrancescoScandiffio/shop-totem/blob/01032fd063a5e3aec5fd446695bc2223c996a132/raffaelliscandiffio.shop-totem/src/main/java/com/github/raffaelliscandiffio/controller/TotemController.java#L103-L113
If the addition of this panel is confirmed, we have to discuss where and how to redirect the user to start a new shopping session.
I think it would be nice to add a button pointing to the shopping page and a timer of a few seconds that automatically redirects to the welcome page when it goes off, i.e if "new shopping" isn't clicked before the timer goes off. However, at the moment there are other things to do with higher priority than the timer which I would tag as an optional addition. 
cc @ClaudiaRaffaelli

**Comment by ClaudiaRaffaelli** [comment]
I would say that definitely the addition of the GoodBye panel is confirmed. It is indispensable for enabling the user to obtain feedback regarding the successful completion of the order. 
As for the "new shopping" button placed in the GoodBye page, I agree to link it to the Shopping page, skipping the Welcome, which would add no value for the new user who intends to start a fresh order.
 I also like the idea of the timer, but as you said for the moment I would postpone it.
