### ISSUE TITLE
Messages intended for different panels are instead displayed on the same panel

### ISSUE THREAD

**Issue by FrancescoScandiffio** [FrancescoScandiffio/shop-totem#28]
I noticed that methods that are supposed to send messages to different panels instead invoke the same function which sends them to the same panel. 
A product can be bought only from the shopping view and a cart item can be returned only from the cart view. However, both methods `TotemController.buyProduct` and `TotemController.removeItem` invoke `TotemView.showMessage`
- buyProduct
https://github.com/FrancescoScandiffio/shop-totem/blob/01032fd063a5e3aec5fd446695bc2223c996a132/raffaelliscandiffio.shop-totem/src/main/java/com/github/raffaelliscandiffio/controller/TotemController.java#L74
- removeItem
https://github.com/FrancescoScandiffio/shop-totem/blob/01032fd063a5e3aec5fd446695bc2223c996a132/raffaelliscandiffio.shop-totem/src/main/java/com/github/raffaelliscandiffio/controller/TotemController.java#L83

The implementation of `showMessage` shows the input message on the shoppingView
https://github.com/FrancescoScandiffio/shop-totem/blob/01032fd063a5e3aec5fd446695bc2223c996a132/raffaelliscandiffio.shop-totem/src/main/java/com/github/raffaelliscandiffio/view/swing/TotemSwingView.java#L154-L157

This issue comes from the first interface design where we had planned a single JFrame with both the product list and the shopping cart to be in a single frame, along with a single label for messages. Although the code is correct from a unit test point of view - and at the moment we only have unit tests - this is not the desired behaviour and an integration or e2e test on this would surely fail.

**Comment by FrancescoScandiffio** [comment]
My suggestion is to split `showMessage` and make the view expose `showShoppingMessage` and `showCartMessage`. In this way, the controller invokes the method related to the ongoing operation without the need to know things such as the name of the panel on which the message has to be displayed. Maybe something like the following **pseudocode**
```
public showCartMessage(String msg){
    get cart panel
    showMessage(cartPanel, msg); 
}

public showShoppingMessage(String msg){
    get shopping panel
    showMessage(shoppingPanel, msg); 
}

private showMessage(panel, msg){
    panel.getLabel.setText(msg)
    panel.getLabel.setColor(Black)
}
```

cc @ClaudiaRaffaelli

**Comment by ClaudiaRaffaelli** [comment]
Looks good to me.
